"""RAGTruth Label Mapper — replaces Stages 1 and 2 of the pipeline.

For RAGTruth we skip LLM generation (responses already exist in the dataset)
and skip NLI-based entropy (ground-truth hallucination labels are provided).

This script:
  1. Loads wandb/RAGTruth-processed from HuggingFace.
  2. For each sample, runs one low-temp forward pass through the LLM to extract
     TBG and SLT embeddings (needed by extract_all_layers.py / train_probe.py).
  3. Writes output/ragtruth/generations.pkl  — same schema as run_qa_generation.py.
  4. Writes output/ragtruth/nli_labels.json  — entropy=0.0 (non-hallucinated)
     or entropy=1.0 (hallucinated), matching the schema read by extract_all_layers.py
     and train_probe.py.  best_split will find threshold=0.5 automatically.

Usage:
    python map_ragtruth_labels.py
    python map_ragtruth_labels.py --num_samples 500 --split test
"""
import os
import sys
import gc
import json
import pickle
import logging
import argparse

import torch
import numpy as np
from collections import Counter
from tqdm import tqdm
from datasets import load_dataset

sys.path.append(os.path.join(os.path.dirname(__file__), "semantic_uncertainty"))

from uncertainty.models.huggingface_models import HuggingfaceModel
from common_utils import (
    MODEL_NAME, TEMPERATURE_LOW, MAX_NEW_TOKENS,
    OUTPUT_BASE, SEED_QA,
)

logging.basicConfig(
    format='%(asctime)s - %(levelname)s - %(message)s',
    level=logging.INFO
)

DATASET_NAME = "ragtruth"
HF_DATASET   = "wandb/RAGTruth-processed"


def parse_args():
    parser = argparse.ArgumentParser(description="RAGTruth label mapper (pipeline stages 1+2)")
    parser.add_argument("--num_samples", type=int, default=None,
                        help="Cap number of samples (default: all)")
    parser.add_argument("--split", choices=["train", "test"], default="test",
                        help="Which RAGTruth split to process (default: test)")
    parser.add_argument("--checkpoint_every", type=int, default=100,
                        help="Save checkpoint every N samples")
    return parser.parse_args()


def extract_label(row):
    """Return 1 if either hallucination type is flagged, else 0."""
    labels = row.get('hallucination_labels_processed') or {}
    return int(
        labels.get('evident_conflict', 0) == 1 or
        labels.get('baseless_info', 0) == 1
    )


def build_prompt(row):
    """Use input_str if available, else construct from context + query."""
    input_str = (row.get('input_str') or '').strip()
    if input_str:
        return input_str
    context = (row.get('context') or '').strip()
    query   = (row.get('query')   or '').strip()
    if context:
        return f"Context: {context}\nQuestion: {query}\nAnswer:"
    return f"Question: {query}\nAnswer:"


def main():
    args = parse_args()

    output_dir  = os.path.join(OUTPUT_BASE, DATASET_NAME)
    os.makedirs(output_dir, exist_ok=True)
    gen_file    = os.path.join(output_dir, "generations.pkl")
    nli_file    = os.path.join(output_dir, "nli_labels.json")

    # ------------------------------------------------------------------ #
    # 1.  Load RAGTruth                                                    #
    # ------------------------------------------------------------------ #
    logging.info(f"Loading {HF_DATASET} (split={args.split}) ...")
    raw = load_dataset(HF_DATASET)[args.split]

    # Keep only outputs generated by Llama-2-7B-Chat (our probe model).
    raw = raw.filter(lambda x: 'llama-2-7b-chat' in str(x.get('model', '')).lower())
    logging.info(f"After model filter (llama-2-7b-chat): {len(raw)} samples.")

    if args.num_samples is not None:
        raw = raw.select(range(min(args.num_samples, len(raw))))

    logging.info(f"Processing {len(raw)} samples.")

    # ------------------------------------------------------------------ #
    # 2.  Load LLM (needed only for TBG/SLT embedding extraction)         #
    # ------------------------------------------------------------------ #
    logging.info(f"Loading model: {MODEL_NAME} ...")
    model = HuggingfaceModel(
        model_name=MODEL_NAME,
        stop_sequences='default',
        max_new_tokens=MAX_NEW_TOKENS,
    )

    # ------------------------------------------------------------------ #
    # 3.  Per-sample forward pass                                          #
    # ------------------------------------------------------------------ #
    data_store = []
    nli_output = []

    for i, row in enumerate(tqdm(raw)):
        label   = extract_label(row)
        prompt  = build_prompt(row)
        output  = (row.get('output') or '').strip()
        context = (row.get('context') or '').strip()
        query   = (row.get('query')   or '').strip()
        row_id  = str(row.get('id', i))

        tbg_embedding = None
        slt_embedding = None
        ml_answer = ""

        try:
            # Low-temp forward pass: capture the model's own generated answer
            # (used as most_likely_answer so causal validation compares model
            # output vs gated output, not dataset output vs gated output).
            ml_answer, _, hidden_states, _ = model.predict(
                prompt,
                temperature=TEMPERATURE_LOW,
                return_latent=True,
            )
            _, slt_embedding, tbg_embedding = hidden_states
        except Exception as e:
            logging.error(f"Sample {i}: embedding extraction failed — {e}")

        # accuracy: compare model's low-temp answer against the reference output.
        # Uses token-F1 >= 0.5 (same as inference_with_gate.py for QA).
        def _tok_f1(pred, ref):
            p, r = pred.lower().split(), ref.lower().split()
            if not p or not r:
                return 0.0
            common = sum((Counter(p) & Counter(r)).values())
            if common == 0:
                return 0.0
            return 2 * common / (len(p) + len(r))
        accuracy = 1.0 if _tok_f1(ml_answer, output) >= 0.5 else 0.0

        data_store.append({
            "sample_index":      i,
            "dataset_index":     i,
            "id":                row_id,
            "question":          query,
            "context":           context if context else None,
            "answers":           [output],
            "prompt_used":       prompt,
            "generations":       [output],   # pre-existing reference response
            "most_likely_answer": ml_answer,
            "accuracy":          accuracy,
            "tbg_embedding":     tbg_embedding,
            "slt_embedding":     slt_embedding,
        })

        # entropy=0.0 → confident (label 0), entropy=1.0 → hallucinated (label 1)
        # best_split in train_probe.py will find threshold=0.5 automatically.
        nli_output.append({
            "sample_index": i,
            "question":     query,
            "entropy":      float(label),
            "num_clusters": 1,
        })

        if (i + 1) % 10 == 0:
            gc.collect()
            torch.cuda.empty_cache()

        if (i + 1) % args.checkpoint_every == 0:
            with open(gen_file, "wb") as f:
                pickle.dump(data_store, f)
            with open(nli_file, "w") as f:
                json.dump(nli_output, f, indent=2)
            hallucinated = sum(d['accuracy'] == 0.0 for d in data_store)
            logging.info(
                f"Checkpoint {i+1}/{len(raw)} — "
                f"hallucinated={hallucinated}, non-hallucinated={len(data_store)-hallucinated}"
            )

    # ------------------------------------------------------------------ #
    # 4.  Final save                                                       #
    # ------------------------------------------------------------------ #
    with open(gen_file, "wb") as f:
        pickle.dump(data_store, f)
    with open(nli_file, "w") as f:
        json.dump(nli_output, f, indent=2)

    hallucinated     = sum(d['accuracy'] == 0.0 for d in data_store)
    non_hallucinated = len(data_store) - hallucinated
    missing_emb      = sum(1 for d in data_store if d['tbg_embedding'] is None)

    logging.info(f"Done. Saved {len(data_store)} samples to {output_dir}")
    logging.info(f"  hallucinated={hallucinated}, non-hallucinated={non_hallucinated}")
    logging.info(f"  samples missing embeddings: {missing_emb}")
    logging.info(f"Next steps: extract_all_layers.py --dataset ragtruth")
    logging.info(f"            extract_lookback_features.py --dataset ragtruth")


if __name__ == "__main__":
    main()
